services:
  simple-issue-tracker:
    image: ghcr.io/thedinz/sit:latest
    container_name: simple-issue-tracker
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATA_DIR: /data
    volumes:
      - ./storage/db:/data/db
      - ./storage/uploads:/data/uploads
      - ./storage/logo:/data/logo
      - ./storage/backups:/data/backups
